### ISSUE TITLE
Punch List: Artifact

### ISSUE THREAD

**Issue by iamwillbar** [spdx/spdx-3-model#10]
This is a punch list of open questions from the 2021-12-07 Tech Team meeting. Please comment on this issue with any discussion, proposed answers, or additional questions you have:

- [ ] Should this have a Created property, distinct from the creation time of the Element?
- [ ] Should we separate create time of actual file, vs creation of meta data (element) about the actual file?
- [ ] Should created by 
- [x] Created time on reproducible builds?   New SBOM for exactly same set of inputs?   What are the use cases where it is used?
- [x] How are elements created related to contextual collection?   Creation date on collection. 
- [x] Could an SBOM be considered an Artifact? 
- [x] How do ranges of artifacts get represented?  Is it only packages? 
- [ ] Do artifacts have to be "real"?   Expressing version ranges that don't yet exist?   ie.  future? 
- [ ] It depends on a version range, but we can't tell you what it is?   PURLS, CPEs, wildcards, how handle.
- [x] Common set of relationships between artifacts - ie. files associated with package.  Overlapping with relationships - document? handle in serialization specification?   How do we model this?  Example: Snippet is from file becomes "contains". Direct properties vs. handle. Example if creation an SBOM that only had an annotation, need from as well as to.

**Comment by davaya** [comment]
An SBOM created by Bob has new creationInfo even if it has exactly the same set of inputs as an SBOM created by Alice.  Bob is not following best practices if he does create a new SBOM instead of re-using Alice's.

An SBOM is a File with a filePurpose of BOM.

It must be possible to create an SBOM that has only one or more annotations (or only one or more Identities, or only one or more Licenses).  Annotation has "subject" and can be applied to existing Elements.  Relationship has "from" and "to" and can be applied to existing Elements.  Identity is referenced from Artifact/originator and Element/Created/by and must exist at the time it is referenced.

License is currently undefined; it presumably must exist if referenced by Elements (like Identity) rather than being applied to existing Elements (like Annotation and Relationship).

**Comment by jeff-schutt** [comment]
Group discussed software artifact creation date on the call today. Proposal that we aggregate this and other related metadata generated by and/or describing the build system in an new profile: a Build Infrastructure BOM profile.

**Comment by kestewart** [comment]
Created description has been reworked so reproductible buils are possible.

**Comment by kestewart** [comment]
Closeing this out for now,  revisit in future for 3.1.
