### ISSUE TITLE
Punch List: Document

### ISSUE THREAD

**Issue by iamwillbar** [spdx/spdx-3-model#15]
This is a punch list of open questions from the 2021-12-14 Tech Team meeting. Please comment on this issue with any discussion, proposed answers, or additional questions you have:

- [x] Are we losing any information compared to 2.2 when serialized.
- [x] Should it be considered as an Artifact? Document artifact is a collection of elements and can refer to as an artifact.    
- [x] Is it to describe the document or is it a document?  
- [x] Can you serialize a single element by itself?  
- [x] Should namespace be in a collection or a Document? A document represents a serialization of one or more elements and is namespace specific. 
- [x] External map - how does it relate to a collection.   Document inherits collection, Collection is abstract. 
- [x] Namespace map should go on document because they are specific to serialization.
- [x] Why would you have a BOM rather ContextualCollection?
- [x] Henk:  Document and contextual collection have no semantic difference, when doing the model.  Parsers trying to automate may have concerns. William: the semantic is the definition.  
- [x] Contextual collection:  shared context.  Does not represent a serialization.
- [x] Document: no implication that there is a shared context.   Represents a serialization.  You can checksum it.   It is physical, and namespaces.   Does not need to contain an SBOM at all - it could be a list of licenses. 
- [x] Does the document represent some form of serialization for verification?  So that it can be referred to in the future?  Round tripping (meta data about the serialization is important). 
- [x] Documentation being serialized representation of elements, makes more sense to show as an artifact.   Could have a stream artifact.   Collection says that this set of bytes has these elements in it.  Document is the stream of bytes. 
- [x] An element called document does not appear in a serialized set of bytes.  License elements. 
- [x] An annotation has creator, summary, etc. 
- [x] A single Annotation Element has creation info. Five annotation Elements each have their creation info that may be the same or different.  One or more Elements can be serialized into document bytes.  Those bytes are described by a File (Artifact) Element that has creation info for the aggregation separate from its members.
- [x] Reasons why Meta data about the serializations:   Data licensing, Copyright, Round tripping, ....
- [x] Is it necessary for data licenses to be involved in document?  (related to serialized bytes).
   * Element license represents for the element, not for the document collection.   Not comfortable can be solved in a contextual collection.
- [x] Can the license info for the serialized data be a property of the collection.

**Comment by davaya** [comment]
The logical model includes some purely serialization-related detail because there is not a formal physical information model.  Document is the interface between logical Elements and physical serialized collections of elements, so addressing this issue means "Should SPDX define an information (syntax-agnostic serialization) model?

The workflow would be:
1) there are a bunch of individual logical Elements, each with their own creation info
2) "Gary" serializes exactly 15 element values into a file
3) "Steve" serializes the same 15 element values into two files
4) the files exist, so someone can now create three more Artifact Elements - "Gary's file", "Steve's file1" and "Steve's file2".  Gary and Steve could create their Artifact Elements simultaneously with (having the identical creation info as) any Elements they create while serializing their files

A "file" is a sequence of bytes, which is a "document".   A specific type of file/document is a set of serialized SPDX Elements, as distinguished from any other type of document.

The logical model could:
a) reuse File with filePurpose=BOM and mediaType=application/spdx+"serialization-format"
b) define SpdxDocument as extending Artifact with an "elements" property containing the IRIs in the serialized file, a mediaType property, but no purpose because it's purpose is known.

The SpdxDocument Element for "Gary's file" would list 15 IRIs in its elements property.  The two SpdxDocument Elements for "Steve's file1" and "Steve's file2" would list the 10 + 5 IRIs (or 10 + 10 if five of the Elements are serialized in both files).

The SpdxDocument Element for Gary's file is not serialized into Gary's file, it is just an Artifact Element that describes Gary's file.  An application that needs to retrieve and validate IRI "x" learns which file to retrieve because SpdxDocument lists the Elements serialized into each file.

At the logical level there is no reason to define Document/NonContextualCollection or ContextualCollection at all, and SpdxDocument is the replacement for BOM.  The "collection" semantics of BOM is achieved using the "elements" property of SpdxDocument.

**Comment by kestewart** [comment]
Discussed with William, updated punchlist and closing this out.
