### ISSUE TITLE
Punch List: NamespaceMap

### ISSUE THREAD

**Issue by iamwillbar** [spdx/spdx-3-model#19]
This is a punch list of open questions from the 2021-12-14 Tech Team meeting. Please comment on this issue with any discussion, proposed answers, or additional questions you have:

- [x] Is there a default namespace?   Will empty prefix suffice?
- [x] Namespace map can have explicit or blank prefix - can a blank prefix refer to all the documents in the document?   Elements in a document can be from any namespace.
- [x] How does the namespace map, interact with External map?  External map has integrity map. Validation
- [x] Should namespace map be on collection or document?

**Comment by davaya** [comment]
* A Document Element describes a document entity.
* The "id" IRI of the Document Element is the default namespace within the document entity it describes.
* If a namespace map is serialized in document A, then the IRI corresponding to a prefix for document B is the default namespace within document B.
* Although Namespace map could have a blank prefix representing a document's default namespace, it is messy to say "blank prefix IRI" instead of "namespace" or "baseIRI", and even messier to say that the blank prefix IRI is required while other prefixes are optional.  In the logical model "namespace" and "namespaceMap" should be separate properties, with no blank prefix.
