### ISSUE TITLE
Licensing: How to add new properties to an existing class?

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-3-model#218]
Question for (I think) @zvr and @armintaenzertng:

In the licensing profile / namespace / whatever, we defined properties like `concludedLicense` which can be applied to a `Package`, `File` or `Snippet`, which are defined in the Software profile / namespace.

Two questions for how to represent this in the SPDX 3.0 MarkDown files:

1. From the Licensing namespace model files, how do I indicate that a property like `concludedLicense` is _available_ for use as a field on Packages, Files and Snippets?
2. For the Licensing profile _restrictions_, how do I indicate that a `concludedLicense` is _required_ to be present for all Packages, Files and Snippets in an SPDX Document, if it is going to conform to the "Licensing profile"?

cc @goneall @kestewart for visibility

**Comment by zvr** [comment]
@swinslow :

1. You modify the original files (in `/Software`) and add the property in the classes, making it optional
2. You then add an "External properties restrictions" section to your class(es), specifying that these properties should have `minCount: 1`.

See #170 for an example I pushed a couple of weeks ago.


However... since you want to have this in all of `Package`, `File` and `Snippet`, is it worth it to simply have it on `Artifact` ?

**Comment by maxhbr** [comment]
I am not sure that one can add "External properties restrictions" to `/Software/Package` if licensing is enabled, without extending it. in #170 it worked, since the class applying the restriction extended the base. Or in other words: which file in the Licensing profile would contain this restriction?

**Comment by swinslow** [comment]
Thanks @zvr -- not sure I fully understand. If the properties are defined in the Licensing namespace, would we still be specifying them on these classes in the Software namespace? This may be similar to @maxhbr's question above too. I'll plan to ask this on the tech team call today.

**Comment by zvr** [comment]
Ah, ok. There are no specific classes.

OK, let's put the info on the top-level "namespace" file then.

**Comment by swinslow** [comment]
I believe this was handled with #286 and #291, so I'm going to go ahead and close this. Please feel free to re-open if I'm incorrect!
