### ISSUE TITLE
Licensing: PackageLicenseInfoFromFiles is missing

### ISSUE THREAD

**Issue by tsteenbe** [spdx/spdx-3-model#303]
Noticed [PackageLicenseInfoFromFiles](https://spdx.github.io/spdx-spec/v2.3/package-information/#714-all-licenses-information-from-files-field) is missing in the SPDX 3.0 License Profile. Propose to bring back this field in some form so SPDX users can migrate from 2.x to 3.x without losing data (users with SBOM with only package-level information).

**Comment by swinslow** [comment]
cc @jlovejoy 

From SPDX 2.3 spec, [section 7.14.1](https://spdx.github.io/spdx-spec/v2.3/package-information/#714-all-licenses-information-from-files-field):

> Cardinality:
> * 0..* (optional) if FilesAnalyzed (7.8) is true or omitted
> * 0..0 (must be omitted) if FilesAnalyzed is false.

In SPDX 2.3 and earlier, an SBOM with only package-level information (e.g. where FilesAnalyzed is false) cannot have this field present.

For an SBOM where FilesAnalyzed is true, I _think_ this field is redundant even in SPDX 2.3 with the existing License fields for Files: it's basically just a reprocessed listing of the licenses from the Files contained in that Package, with ANDs and ORs stripped out.

Given that, if this field is removed, where is the data loss in migrating from SPDX 2.3?

**Comment by goneall** [comment]
@swinslow The semantics are a bit different.  The LicensingInfoInFiles are typically discovered by matching licenses whereas the declared license is copied from the package level information.

Some people are using the LicenseInfoInFiles to represent detected licenses from tooling which is useful in some cases.

I'm thinking we should keep it in as an optional field.

**Comment by swinslow** [comment]
I'm open to discussing whether to keep it in as an optional field. I lean towards leaving it out unless it is necessary, with my thoughts being:
1. wanting to minimize the number of Package-specific, File-specific or Snippet-specific licensing fields;
2. wanting to minimize confusion from having multiple licensing fields to the extent their meanings overlap; and 
3. wanting to avoid duplicating information across fields in a way that can lead to inconsistencies -- if one can be generated from the other, then may be preferable to just keep one of them.

For [the new definition of `declaredLicense`](https://github.com/spdx/spdx-3-model/blob/main/model/Software/Properties/declaredLicense.md), here's what it says:

> * for Packages:
>   * would include license info describing the license of the Package as a whole, when it is found in the Package itself (e.g., LICENSE file, README file, metadata in the repository, etc.)
>   * would not include any license information that is not in the Package itself (e.g., license information from the project’s website or from a third party repository or website)
> * for Files:
>   * would include license info found in the File itself (e.g., license header or notice, comments, SPDX-License-Identifier expression)
>   * would not include license info found in a different file (e.g., LICENSE file in the top directory of a repository)

So I think a File's `declaredLicense` in 3.0 is the equivalent of `LicenseInfoInFile` from 2.3 and earlier: it's the license info found in each file.

A `PackageLicenseInfoFromFiles`, then, would be equivalent to taking all of the File's declaredLicenses, removing the ANDs and ORs, and removing duplicates.

If the goal is to have this at the Package level but without needing to specify licenses for Files, then if I'm understanding correctly, that isn't a 2.3 to 3.0 compatibility or migration issue -- because in 2.3 you can't use this property unless you're listing the Files for the corresponding Package.

So I'm open to the community looking at whether this is something that should be present in 3.0. But I guess I'm unclear whether this is in fact resulting in a loss of data for 2.3 => 3.0 conversion, given the constraints on using this field in 2.3.

**Comment by goneall** [comment]
@zvr any thoughts on this one?

**Comment by swinslow** [comment]
@goneall Just to add since my comments from May -- now that the team has moved from treating license information as relationships rather than properties, I'm not sure how this would work. Would the intent be to have a `PackageLicenseInfoFromFiles` relationship type?

**Comment by swinslow** [comment]
Thanks @goneall. Just to be clear, I'm _not_ in favor of adding it even as a relationship.  :)  As I described above I don't think that removing the existing field would present a data loss issue, at least based on how it's defined in 2.x. (I could be wrong! But my read of it is that it's already satisfactorily handled by the existing fields in 3.0 and that adding it would be generally redundant with data that would already need to be present for a direct 2.x-to-3.0 translation.)

I'm fine with getting further community input, just wanted to clarify that I am not currently in favor of adding this as a relationship or otherwise.

**Comment by jlovejoy** [comment]
As far as this field being missing as per @tsteenbe original comment and whether it's really needed as per @swinslow comments. I have a few thoughts to add:
1) I also question the value of this field (I always have) - now that we are ~14 years in, it'd be interesting to see how, if at all, this field is used in practice
2) it is an odd field given that it has to do with information at the file level but is part of the package section... how did I miss this? maybe in the new 3.0 format, this doesn't matter
3) @tsteenbe - mentions potential loss of data - can you explain the details of this?

**Comment by goneall** [comment]
Note: I updated the [Migration Guide](https://docs.google.com/document/d/1-olHRnX1CssUS67Psv_sAq9Vd-pc81HF8MM0hA7M0hg/edit#heading=h.uzojmh0kkl) with a [rationale for the removal of this property](https://docs.google.com/document/d/1-olHRnX1CssUS67Psv_sAq9Vd-pc81HF8MM0hA7M0hg/edit#heading=h.iju103mqyox3) to suggest adding an Annotation to preserve the old data.

**Comment by goneall** [comment]
Based on the questions and discussion above, I tend to agree that we can remove the property.

**Comment by zvr** [comment]
I also agree that there is no need for such a property in SPDXv3.

**Comment by goneall** [comment]
Based on the above comments, I'll go ahead and close this issue.
