### ISSUE TITLE
How to require CreationInfo without inflating the size of serialized data

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#306]
The `creationInfo` is a property of `Element` with a current cardinality of `0..1`.  We should require `creationInfo` at least once per serialization for validation and integrity purposes.  However, changing the cardinality to `1..1` would significantly increase the size of the serialized SPDX data.

**Comment by zvr** [comment]
Not really; in the serialization meetings we've talked about re-using a single `CreationInfo` structure (if it's the same for a number of Elements).

**Comment by maxhbr** [comment]
I think there are currently several options discussed:
1. making it mandatory for some collections, like SpdxDocument or Sbom
1. making it mandatory for all elements and using the `@id` of the creation info for deduplication. E.g. by using the line `"creationInfo": "my_namespace_prefix:110856b8-bd44-4eed-ad03-16c7dbc2cbe3"` in every Element
1. making it mandatory for all elements and using some magic which implicitly applies the creation info from the parent collection to contained elements.
1. adding something to the top level of the serialization that contains the default / fallback creationInfo


### Problems with 1.
One might just serialize a single bare element, and there the requirement would not be enforced.

### Problems with 2.
This adds complexity and noise which needs to be handled by tools. It is also hard to read.

### Problems with 3.
This is magic that is unclear. @sbarnum mentioned that this should be possible.

Elements might be contained in multiple collections.

### Problems with 4.
Might not be easy to add to RDF / JSON-LD. Adds an layer of custom de-serialization logic around already complex RDF.

**Comment by maxhbr** [comment]
related issue: https://github.com/spdx/spdx-3-model/issues/357

**Comment by davaya** [comment]
This issue is caused by trying to mix the logical model with serialization.  We need to agree on what the logical model means.

* logically creation information info is required for every Element - an element can't exist if it wasn't created
* physically we don't want multiple copies of the same info

Both can be achieved if we can agree not to try to represent serialized data in the logical model.

**Comment by davaya** [comment]
#4 is not a problem for RDF/JSON-LD, because they wouldn't use it.  RDF serialization specifies how the elements are retrieved from an RDF payload, JSON serialization specifies how they are retrieved from a JSON payload, and in both cases the deserialized values must be identical (if the logical model defines logical values).

If the logical model is viewed as defining serialized data, that's a whole 'nother problem - it isn't a logical model, and deserializing RDF data will yield a different result than deserializing JSON data or lawyer-readable data.

**Comment by davaya** [comment]
Option 4 is not a problem for RDF or JSON-LD or Turtle because they wouldn't use it.  RDF serialization specifies how the elements are retrieved from an RDF payload, JSON serialization specifies how they are retrieved from a JSON payload, and in both cases the resulting elements must be identical because that's what "logical values" means.  Armin's dataclasses-based Python objects are logical values, as are the equivalent Element classes in Go or Java or Rust.

If the model is viewed as defining serialized data that's a whole 'nother problem, because it's no longer a logical model. Parsing RDF data will yield a different result than parsing JSON data or parsing lawyer-readable data.

First we must agree on whether the model defines logical elements (graph node values) or serialized files.  Without answering that question the various solutions will never converge because they solve different problems.

**Comment by davaya** [comment]
Option 4 is not a problem for RDF or JSON-LD or Turtle because they wouldn't use it.  RDF serialization specifies how the elements are retrieved from an RDF payload, JSON serialization specifies how they are retrieved from a JSON payload, and in both cases the resulting elements are identical because that's what "logical values" means.  Armin's Python Element classes are logical values generated from the logical model, as are the model-defined Element classes in Go or Java or Rust.  The methods for various data formats are hidden but the element values must be the same - it's the result that counts.

If the model is viewed as defining serialized data that's a whole 'nother problem, because it's no longer a logical model. Parsing RDF data will yield a different result than parsing JSON data or parsing lawyer-readable data.

First we must agree on whether the model defines logical elements (class variables representing graph nodes) or serialized files.  Without answering that question the various solutions will never converge because they solve different problems.

**Comment by davaya** [comment]
Option 4 is very similar to option 2, except that the namespace map and creation info map define local IDs (prefixes like "n1" or "c1" for namespaces and creationInfos) rather than full RDF IRIs:

`2.` making it mandatory for all elements and using the @id of the creation info for deduplication. E.g. by using the line `"creationInfo": "my_namespace_prefix:110856b8-bd44-4eed-ad03-16c7dbc2cbe3"` in every Element
`4.` making it mandatory for all elements and using a local id of the creation info for deduplication. E.g. by using the line `"creationInfo": "c1"` in every Element except those where the mandatory creationInfo property has the default value

As we discussed for namespaceMap where a default entry would have the blank key `"": "http://blah.blah.blah"` and ids with the default prefix would be serialized with no `prefix:`, elements with the default CreationInfo with the blank key would be serialized with no creationInfo property.

If the serialized data has no namespaceMap, every spdxId must be the full IRI.  
If the serialized data has no creationInfoMap, every element must have the full creationInfo property, and the payload is just a list of full elements like @sbarnum 's [first example](https://github.com/spdx/spdx-3-model/issues/357) - fully-expanded serialization:
```
{
  "element": [
    "... (element1)",
    "... (element2)"
  ]
}
```
For Gary's use case of a large number of elements being created and serialized at the same time, the serialized file would have a single creationInfoMap with the default creation info.  No elements, collection or otherwise, would have a creationInfo property:
```
{
  "namespaceMap": {
    "": "https://spdx.dev/elements/3F26391C#"
  },
  "creationInfoMap": {
    "": {
      "specVersion": "3.0.0",
      "profile": ["core"],
      "created": "2023-06-02T13:49:24+00:00",
      "dataLicense": "CC0-1.0",
      "createdBy": ["spdx-dev"]
    }
  },
  "element": [
    "... (element1)",
    "... (element2)"
  ]
}
```

**Comment by goneall** [comment]
Since this is solved for JSON-LD using the anonymous nodes for `creationInfo` just in the serialization, this can be closed.
