### ISSUE TITLE
Consider making datasetType an enum instead of String

### ISSUE THREAD

**Issue by willarmiros** [spdx/spdx-3-model#363]
Currently, the [datasetType](https://github.com/spdx/spdx-3-model/blob/main/model/Dataset/Properties/datasetType.md) property is a string. Instead, we could consider introducing a new vocabulary enumerating different Dataset types, and change the property to be a list of these options instead of just a string. We would use a List instead of just one to account for multi-modal datasets (which could have multiple types).

For the list of types, I have this list borrowed this from [Wikipedia](https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#List_of_sorting_used_for_Datasets):
* Tabular
* Graph
* Text
* Image
* Sound
* Video
* Other

Happy to make a PR if this seems like an acceptable change!

**Comment by bennetkl** [comment]
We went with a string, since there are a few more data types for AI applications then are listed on wiki and lists continues to grow.  Here are a few more to consider .. Numeric Data,  Categorical Data is a type of data that is used to group observations into distinct categories, Time Series Data, would prefer Audio Data instead of sound, Sensor (or biometrics) Data, maybe change tabular to structured data (so it includes databases as well), Syntactic Data,  Timestamp Data,   I was just going to put in a pull request to have some examples (since 'string' is vague), but if having an enum makes it easier for tool development, then let's go for it. I'm wondering if in the "other" that they need to list the data type and then overtime, we can get a clearer picture of the types of data used by AI applications.

**Comment by willarmiros** [comment]
Hi @bennetkl - I agree with your suggestions for changing/adding to my list of types. Only questions are:

1. What is the difference between time series data and timestamp data?
2. How would you like to implement allowing a string if the user chooses "Other"? In existing vocabularies like [HashAlgorithm](https://github.com/spdx/spdx-3-model/blob/134a9e6193c108764320a9ca43a6b8b39ad47e11/model/Core/Vocabularies/HashAlgorithm.md), I don't think a string option exists when "Other" is chosen. It might make sense to suggest users open a GH issue if their data type isn't included.

I'm happy to open a PR for this once we get the above clarified!

**Comment by willarmiros** [comment]
Per discussion with @bennetkl at the AI + Data profile meeting on 6/7/23:

1. time series data is something like a time-series DB, wherein each entry is a recorded observation over time, such as stock data. Timestamp data is a collection of events that have timestamps, but is not necessarily part of a timeseries (e.g. several events could have the same timestamp, no fixed intervals between timestamps)
2. We can just leave "Other" as it's implemented in other enums

Overall the profile working group is open to this proposal, so I will open a PR to support this.

**Comment by willarmiros** [comment]
Full list:

- Structured (including tabular)
- Numeric
- Categorical
- Graph
- Timeseries
- Timestamp
- Text
- Sensor (including biometrics)
- Image
- Syntactic
- Audio
- Video
- Other
- NoAssertion

**Comment by kestewart** [comment]
Thanks for the detailed notes.   Looks like my open question about if Karen and Gopi had seen this is resolved.    I'll merge in the PR, and we can evolve it from there.
