### ISSUE TITLE
Define Lite profile

### ISSUE THREAD

**Issue by zvr** [spdx/spdx-3-model#384]
There may be need for a _Lite_ Profile. This issue is to document the requirements and decide what has to be added in the model.

@yoshi-i, please provide a description of what you need.

**Comment by zvr** [comment]
It seems the requirements are documented in https://github.com/OpenChain-Project/OpenChain-JWG/blob/master/subgroups/sbom-sg/outcomes/SPDX-Lite/Proposal_v3.0/model/LiteProfile-Requirements.md

**Comment by goneall** [comment]
There is an open PR #350 which is planned to be updated.

**Comment by zvr** [comment]
I _think_ there is going to be a completely new PR. But let's wait and see before closing the old one.

**Comment by yoshi-i** [comment]
Sorry,  due to my careless sync fork operation on my forked repository, PR #350 contains unexpected commits. I've re-issue PR https://github.com/spdx/spdx-3-model/pull/521.
If it better to solve with other method to eliminate unexpected commits on this https://github.com/spdx/spdx-3-model/pull/350, please point it out.

**Comment by yoshi-i** [comment]
@zvr -san,
We've proceeded to new PR #523. May I ask close this issue item?
