### ISSUE TITLE
Just for inspiration, a (maybe) equivalent model using composition instead of inheretance

### ISSUE THREAD

**Issue by maxhbr** [spdx/spdx-3-model#40]
(This is very WIP)

Hey,

just some brainstorming, that I am doing in https://github.com/maxhbr/spdx-3-model.compositional. I tried to implement (just for fun) the current state of SPDX3 model https://github.com/spdx/spdx-3-model/commit/92c25fcb420934c5b32f7809cd46fc12d3d6182d multiple times and I failed in the complicated inheritance. Especially when trying to add a second profile it fall apart. I had more success when using the following compositional model (Element is a `sealed trait` or `Enum` or `algebraic datatype`):
![model](https://user-images.githubusercontent.com/1187050/199301312-a09b5500-07b0-4d58-9c95-5e477ff8475f.png)

**Comment by iamwillbar** [comment]
Why wouldn't `_metadata` be on `Element`? By it being on the subclasses we lose any value from inheritance because we can't assume things are true for all `Elements`, only things that have the `_metadata` trait.

The intent is actually to force all elements to have certain capabilities because it's the creators of the documents that decide when they need those capabilities, not the authors of the spec. For example, we want external references and external identifiers to be available on all elements from all profiles.

There are also some incorrect assumptions on this diagram:
* name, summary, description, references, identifiers, extensions aren't "metadata" they are about what the element describes (data) not the element (metadata).
* Annotations can be added after the fact, so the reference needs to be from the annotation to the element not the element to the annotations. 
* Composition requires modifying the class when new types are added so it does not support the addition of profiles well, for example, when the hardware profile comes along Artifact needs to be modified, whereas with inheritance it doesn't. Also, anything that only needs the level of detail at Artifact doesn't need to understand the subclasses.

Not saying that this model isn't possible, they both have tradeoffs, and this is not something we're likely to change this close to the end of 3.0.

**Comment by maxhbr** [comment]
> Why wouldn't _metadata be on Element? By it being on the subclasses we lose any value from inheritance because we can't assume things are true for all Elements, only things that have the _metadata trait.

But this is also true in the other model, where a collection points to elements which might or might not be inlined. Here it is just explicit, that you might not have the element but just a reference. And even without propagating the trait up to the top one can still use patter matching or implement a (partial) function `Element -> ElementMetadata`. And together with context one can even resolve the Metadata for refs.

> The intent is actually to force all elements to have certain capabilities because it's the creators of the documents that decide when they need those capabilities, not the authors of the spec. For example, we want external references and external identifiers to be available on all elements from all profiles.

This is true in this picture. Every non-Ref Element has metadata (mandatory) and that has all the described fields. (A potential thought: This diagram can even do more, it could enforce that every artifact needs to have license information, if license profile is enabled.)

> * name, summary, description, references, identifiers, extensions aren't "metadata" they are about what the element describes (data) not the element (metadata).

that might be a naming issue, maybe it is not `metadata` but `core` or `essentialFields` or maybe it needs to be split up into `metadata` and another set of fields. The important thing is, that it is the common set of fields that is true for all artifacts.

> Annotations can be added after the fact, so the reference needs to be from the annotation to the element not the element to the annotations.

yes, I was lazy here...

> Composition requires modifying the class when new types are added so it does not support the addition of profiles well, for example, when the hardware profile comes along Artifact needs to be modified, whereas with inheritance it doesn't. 

Right now they are modeled as a field `software` which points to the software related data. But it could also be hidden behind a map from name to content or something similar.

> Also, anything that only needs the level of detail at Artifact doesn't need to understand the subclasses.

Same is true for composition, you just need to look at the field that are interesting for you and you can ignore everything else.

**Comment by maxhbr** [comment]
I updated the model (see also https://github.com/maxhbr/spdx-3-model.hs/blob/main/puml/model.png):
![model](https://user-images.githubusercontent.com/1187050/201662200-a39d8409-0570-4842-9503-132a2ea89f78.png)
