### ISSUE TITLE
SPDX NamespaceMap and Document

### ISSUE THREAD

**Issue by davaya** [spdx/spdx-3-model#469]
We discussed this topic at length on the 8/8 tech call, and teed up followup discussions for serialization and tech calls.
Ref: #403, #390

```
SPDX NamespaceMap and Document.    Represent at a different place in model? 
    1)  Specified in the serialization specification for each specialization, and all serializations must support a NamespaceMap
    2) Namespace in ElementCollection  (has been rejected in prior discussion)
    3) Put as a property on SPDX Document (which is a subclass of SpdxCollection)
```

**Terminology:**
  * `Document` is unit of data (as in Word, PDF, XML document).
  * `SPDX Document` is a document containing serialized SPDX data (called `Payload` in the model diagram).
  * `SpdxDocument Element` is an element in the logical model containing metadata about an SPDX Document.

The reason for using the term `Payload` was to reduce confusion between an SPDX Document and the Element describing it. Regardless of terminology, serialized data must be distinguished from logical elements.

**Purpose:**
* The reason to define short prefix strings as abbreviations for longer namespace URIs is to make `Payloads` smaller
* The rationale for including prefix definitions in the logical model is to enable prefixes used in one Payload to be reproduced in another Payload.

**Option 1 requirements:**
* The serialization specification for each document format shall define how to represent the equivalent of [XML document namespaces](https://learn.microsoft.com/en-us/dotnet/standard/data/xml/managing-namespaces-in-an-xml-document) that map prefix strings to URIs within the document:
  * The default namespace URI applies to all unqualified elements in the document
  * Namespace prefixes are declared in the document and apply to all prefixed elements in the document

**Option 1 benefits:**
* All serializations (e.g. tag/value and spreadsheets) have a defined `NamespaceMap` format
  * the SPDX 2.x `documentNamespace` property already defines the default namespace URI
  * in SPDX 2.x a `namespaceMap` property analogous to the `creators` property (e.g., `"Tool: LicenseFind-1.0"`) could define the prefix map entries
* The namespace mapping can be preserved across multiple transformations allowing the original Payload to be recreated
* Every namespace mapping is locally scoped and unambiguous in both directions, supporting transformations that combine elements from multiple SPDX Documents into one
  * "foo" = "http://spdx.org/spdxdocs/spdx-example-444504E0-4F89-41D3-9A0C-0305E82C3301#"  in SPDX Document A
  * "foo" = "http://spdx.org/spdxdocs/spdx-example-12345678-9999-ABCD-9A0C-0305E82C3301#"  in SPDX Document B
  * "bar" = "http://spdx.org/spdxdocs/spdx-example-444504E0-4F89-41D3-9A0C-0305E82C3301#"  in SPDX Document C
  * If Document A and Document C contain the same SPDX Elements using different prefix strings "foo" and "bar" for the same URI, they parse to the identical logical SPDX Elements
  * If Document A and Document B contain the same prefix string "foo" mapped to different URIs, they parse to different logical SPDX Elements without ambiguity or collision

**Comment by goneall** [comment]
Thanks @davaya - I agree with the terminology.

I'll add my requirements and and benefits for option 3.

**Option 3 Requirements**
- If the producer of an SPDX `Payload` wishes to preserve the name space mapping, the `Payload` containing SPDX data will include an `SpdxDocument` element in the `Payload` which includes the  list of `Element`s included in the `Payload` along with the `originalNamespaces` property which maps namespaces to prefixes.
- If the producer doesn't care about preserving the name space mapping, they don't need to do anything - in other words, this is an optional Element
- If an intermediate consumer / producer of an SPDX `Payload` wishes to preserve the name space mapping used in the original `Payload` which includes the `SpdxDocument` element, they would produce a matching `Payload` with the list of elements in the `SpdxDocument`, the `SpdxDocument` element itself, and read the `originalNamespaces` property to encode the name space mapping for whatever serialization format they produce.
- If the intermediate consumer / producer does not wish to preserve the name space mapping, they do not need to.
- The result of an intermediate consumer / producer wishing to preserve the name space mapping must not include more than one `SpdxDocument` due to possible namespace conflicts.  Note that you CAN include multiple `SpdxDocument`s within a serialization, you just can not use the name space mappings for the native output serialization.

**Option 3 Benefits**
- The name space mapping can be preserved across multiple transformations allowing the original `Payload` to be recreated
- Compatibility - preserves the namespace mappings used in SPDX 2.X
- The `originalNamespaces` property can be used as the native map for serializations which do not natively support namespaces (e.g. tag/value and spreadsheets)

**Comment by goneall** [comment]
Since we made a decision on the serialization approach, I'll close this issue to avoid confusion.  There is, however, some nice documentation here we may want to preserve in the minutes.  Since closed issues are not deleted, we can always go back and capture the conversations.
