### ISSUE TITLE
Punch List: Relationship

### ISSUE THREAD

**Issue by iamwillbar** [spdx/spdx-3-model#5]
This is a punch list of open questions from the 2021-12-07 Tech Team meeting. Please comment on this issue with any discussion, proposed answers, or additional questions you have:

- [x] Do One-To-Many relationships have any benefits to offset them being harder to parse as opposed to One-to-One?
- [x] Do we want to simplify relationships to one direction?   Are the semantics documented?  Look at the from (single) / to (one or many) - keep cardinality?  Do we need to remain both directions in the 1:many
- [x] Do we have way its directional or bidirectional?
- [x] Should we convey properties for conveying temporality?
- [x] Is the list of relationship types we have today complete?
- [x] Are there open questions from linking profile discussion?
- [x] How can we express a range of dependencies?  
- [x] How can we express more general conditions?   subclass of relationship with additional semantics?
- [ ] Do we have the relationships we need to describe services?

**Comment by davaya** [comment]
Additional question:

- [ ] How do we express Collection relationships?

Discussion:
* A collection is a list of members; there is a directed relationship between a collection and its members
* The Relationship element has types including CONTAINS and DEPENDS_ON.
* We don't want two ways of expressing Collection relationships - if we retain Collection as a type, we must not define MEMBER_OF as a Relationship type.
* Collection membership is either exclusive or non-exclusive, resulting in a directed tree or a directed acyclic graph of Relationships respectively.  (A person can have only one biological mother or matrilineal ANCESTOR_OF/DESCENDANT_OF tree, a physical component can be used in more than one assembly of components.)
* Collection membership cannot be modified.  Once a Collection Element is minted its list of members cannot be replaced, although a replacement Collection can be minted with a new member list.

Alternatives:
1. Dependency graphs are a common use of non-exclusive collections - delete the DEPENDS_ON/DEPENDENCY_OF Relationship types and use Collection to express dependency.  Dependencies are static.
2. Leave the semantics of Collection undefined except for being static and accept that an Element can be both a MEMBER_OF and a DEPENDENCY_OF a Collection Element.
3. Define the semantics of Collection to specifically exclude all Relationship types - that seems unhelpful.
4. Define the semantics of Collection to specifically include Relationship types known to be static.
5. Delete the Collection type - precludes the generation of Element graphs without traversing relationships, and because relationships are not static the graph is known to be incomplete.

**Comment by davaya** [comment]
**Do we want to simplify relationships to one direction? Are the semantics documented? Look at the from (single) / to (one or many) - keep cardinality? Do we need to remain both directions in the 1:many**
 
Does this mean pruning the list of SPDX v2 RelationshipType values (DESCRIBES / DESCRIBED_BY, CONTAINS / CONTAINED_BY, DEPENDS_ON / DEPENDENCY_OF to include only a single value of each pair?

One artifact can describe many artifacts, and one artifact can be described_by many artifacts - "describe" is semantically a many-to-many relationship.  A many-to-many can be decomposed into a set of one-to-many relationships, in which case both directions of a pair may be needed, or can be decomposed into a set of one-to-one relationships where only one direction is needed.

 **Do we have way its directional or bidirectional?**

???

 **Do One-To-Many relationships have any benefits to offset them being harder to parse as opposed to One-to-One?**
 
 Semantically (at the logical level): No.
 Physically (at the information level): No.
A one-to-many relationship can be efficiently serialized as a one-to-one relationship between one Element and a Collection of Elements.  Only one RelationshipType of a symmetric pair is needed by using a Collection as either the "from" or "to" of a one-to-many.

**Comment by seabass-labrax** [comment]
The currently ongoing discussion at https://github.com/spdx/spdx-spec/issues/610 leads me to think that we should have a `LINK_TO` and `LINK_FROM` relationship for dealing with symbolic links, hard links and Windows shortcut files in SPDX Software Bill of Materials (especially system-level ones).

**Comment by seabass-labrax** [comment]
Would agree with Kate's point made in the 2022-02-15 meeting:
> "we should go ahead with one-directional relationships and see if anything breaks"

**Comment by kestewart** [comment]
For temporality on relationships 
* starting point to consider it as two optional field:  start time stamp & end time stamp.   
* Wildcards assumed by absence of one of the time stamp (ie. no known end time or no known start time. ) 
* If optional fields not present, should NOT assume creation time by default.

Examples:   
* Domain names resolving to IP addresses is a useful case to consider for this.
* Another example is when a company changes name/acquired, etc. 

Minting start time and end time in relationship?  Why not just created time?    
* Context around just the assertion of the relationship.
* Example:  product name was called "Ajax" from 1999-2002,  after that it was called "Car Wash"  Only certain values for certain periods of time,  for period of time making statement about validity.   SBOM is still valid, just the referencing name.  
*  Would like the ability SBOMs over a period of time, regardless of if supplier changed.

**Comment by kestewart** [comment]
Range of dependencies.

Consider it as:   
* A or B or C   
* A 1.0 and A 1.1

Example where we might want to do this is run time dependencies.    
What about the case where we have unknowns in there?   ie. this docker image,  multiple choices.

Z depends on "one of" or "all of"  - type of relationship is defined to convey the completeness of this?
Package manager have some of this already. 

NOTE:   need @iamwillbar & @goneall to weigh in on this.

**Comment by kestewart** [comment]
List of relationships complete?

No.   This isn't something we will ever have.   Also, we're revisiting the set of relationships today in light of directionality.

**Comment by kestewart** [comment]
Relationships to describe Services:
No. we don't have the set we need at this point.

TODO:   Need a proposal of add in relationships that would be useful here.   Open question if this is a 3.0 topic?

**Comment by seabass-labrax** [comment]
Example where optional relationships might apply to more than just runtime dependencies: some projects have more than one build system available. For example, I have come across a project which uses CMake flags to generate either a `Makefile` or a `build.ninja` file. There may be potential security implications of choosing one or the other.

**Comment by iamwillbar** [comment]
From the discussion today we believe the linking profile goals are currently addressed by core (or open punch list items).

**Comment by kestewart** [comment]
Reviewed with William,  all have been settled except services, and we'll decide that then.
