### ISSUE TITLE
SPDX License Version cannot be assigned to `LicenseExpression.licenseListVersion`

### ISSUE THREAD

**Issue by JPEWdev** [spdx/spdx-3-model#529]
`LicenseExpression.licenseListVersion` is defined as a `SemVer`, which is required to have `MAJOR.MINOR.MICRO` fields, but the SPDX license list version is only `MAJOR.MICRO` so it is not possible to assign it to this field

**Comment by zvr** [comment]
Yes, this is known.

In agreement with the Legal Team, the releases of the License List will follow SemVer numbering.

**Comment by maxhbr** [comment]
this means that we can't reference old versions? That is necessary for converting from SPDX-2.x.

**Comment by goneall** [comment]
One note: The current regex isn't correct, the periods need to be escaped

The prior license list versions do not have a patch version which is required in the SEMVer spec

Alternatives:
- Go back to strings
- Shapes can be should - which would create a warning rather than an error
- When migrating from prior license list versions, always add a ".0" as the patch version

We're assuming we need to support prior license list versions.

Consensus on 2 Jan tech call to add a ".0" when migrating from prior versions of the spec or license list.

@maxhbr @JPEWdev - Let me know if you disagree, otherwise we'll include this in the migration documentation and close the issue.

**Comment by zvr** [comment]
@goneall : the pattern in the file _is_ correct (as I've copied it from the upstream definition). The rendering of Markdown somehow  shows `\.` as `.`.  I'm making a note about generating `pattern` in spec-parser.

**Comment by goneall** [comment]
@zvr - good to know - just a rendering issue

**Comment by goneall** [comment]
I updated the migration guide: https://docs.google.com/document/d/1-olHRnX1CssUS67Psv_sAq9Vd-pc81HF8MM0hA7M0hg/edit#heading=h.a4uig77opw1m

Closing this issue as resolved.
