### ISSUE TITLE
How should a blank / empty `copyrightText` be interpreted?

### ISSUE THREAD

**Issue by sschuberth** [spdx/spdx-3-model#655]
In the context of [ORT parsing SPDX files](https://github.com/oss-review-toolkit/ort/issues/7222) the question arose how a given `"copyrightText": ""` for `files` should be interpreted. None of the specs seem to be crystal clear on this. IMO all of these options have some merit:

- interpret a blank / empty `copyrightText` as `NONE`
- interpret a blank / empty `copyrightText` as `NOASSERTION`
- interpret a blank / empty `copyrightText` as a liternal copyright declaration that is empty (even if that does not really add any value)

Currently, ORT simply refuses to parse SPDX files with such `copyrightText` to avoid ambiguity.

Any advice how to handle this case?

PS: The same question basically arises for a set (i.e. present) `licenseConcluded` that is set to an empty / blank string.

**Comment by swinslow** [comment]
Apologies for being slow to weigh in, I hadn't seen this one since it was tagged as Security.

I think the consensus above was to treat an empty (or "trims-to-empty") copyright text string as being equivalent to NOASSERTION? If so, yes, I'm also +1 to that outcome.

I'll put together a quick draft PR to make this explicit.
