### ISSUE TITLE
Clarify description between ExternalIdentifier and ExternalReference

### ISSUE THREAD

**Issue by rnjudge** [spdx/spdx-3-model#705]
https://github.com/spdx/spdx-3-model/blob/main/model/Core/Classes/ExternalIdentifier.md and https://github.com/spdx/spdx-3-model/blob/main/model/Core/Classes/ExternalRef.md have essentially the same definition. It's not clear to me when you would use one over the other.

https://github.com/spdx/spdx-3-model/blob/main/model/Core/Classes/ExternalIdentifier.md is also missing the `SubclassOf` field.

**Comment by rnjudge** [comment]
@sbarnum can you help with the clarification here?

**Comment by goneall** [comment]
I don't have very good bandwidth to do much research / work on this, but I can add a few comments from memory on the difference:
- An identifier should map to only one artifact - in other words, the artifact should be unique relative to the identifier
- The purpose of the identifier is to provide a unique key for the artifact within a domain in order to "identify" the artifact
- A reference is more general, it provides information that is related to the artifact such as a related web page

There is a [section in the migration](https://github.com/spdx/spdx-spec/blob/development/v3.0/docs/annexes/diffs-from-previous-editions.md#external-identifiers) guide that maps the 2.X externalRefs to identifiers.

**Comment by rnjudge** [comment]
@sbarnum @kestewart @goneall I took a stab at clarifying here: https://github.com/spdx/spdx-3-model/pull/710.

**Comment by kestewart** [comment]
Thanks for doing this.   Have merged https://github.com/spdx/spdx-3-model/pull/710 - so closing this now.
