### ISSUE TITLE
In page https://spdx.github.io/spdx-spec/v3.0/model/Licensing/Licensing/ the lists are not displayed correctly.

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-3-model#720]
In page https://spdx.github.io/spdx-spec/v3.0/model/Licensing/Licensing/ the lists are not displayed correctly.

File model/Licensing/Licensing.md

In "for Packages", the next bullets should be indented (nested lists).

In paragraph "A declaredLicense relationship to NoAssertionLicense indicates that one of the following applies", the lists are not created, you have a star instead.

**Comment by zvr** [comment]
Thanks for spotting this, @vargenau ; confirming that this is an issue.
Just to expand on your last point, the list _is_ present, but not rendered as a list, but as running text like `*item one * item two`

Both issues raised are due to different rendering between GitHub internal markdown and the one generated by `mkdocs` I assume. Aren't multiple standards wonderful?

**Comment by bact** [comment]
For the 1st list, nested one, I guess it's because mkdocs Markdown may like to have 4 spaces (or 1 tab) for list indent, instead of 2 spaces. There's an comparability issue here, see: https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md007.md

For the 2nd and 3rd lists (lines 54-58 and lines 79-83), very likely that it is because there's no blank line before the list.
See: https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md032.md

In the case of 2nd and 3rd lists, we should encourage a practice of having blank lines around every list.

**Comment by bact** [comment]
To fix by #723
