### ISSUE TITLE
Do we want / need to have contentType defined in Software and Core?

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#781]
It looks like we have the property `contentType` defined in both the Core and the Software profile.

The definitions look similar.

From doing a bit of research, it looks like both were added with this commit: https://github.com/spdx/spdx-3-model/commit/b1988bfd98f77972f01740556e916461d61237ec

Was this intentional?

If not, should we fix it in the 3.0.1 release?

**Comment by goneall** [comment]
cc: @zvr

**Comment by bact** [comment]
One difference is that

- the `contentType` in Software is describing an object of a **class** (a `File` class)
- the `contentType` in Core is describing another **property** (a `statement` property in `Annotation` class)

**Comment by zvr** [comment]
In Software, `Software/contentType` is being used by `Software/File` to provide the type of the content.

In Core, `Core/contentType` is being used by `Core/ExternalRef` and `Core/Annotation`.

The two definitions seem equivalent; and all instances have range `Core/MediaType`.

I propose we remove the property in Software, and only keep (and use) the definition in Core.

So we need a PR to:
- update the `Core/Properties/contentType.md` with some of the wording of the better written `Software/Properties/contentType.md`
- remove the `Software/Properties/contentType.md` file
- update `Software/Classes/File.md` to refer to `/Core/contentType` instead of `contentType`

**Comment by goneall** [comment]
> I propose we remove the property in Software, and only keep (and use) the definition in Core.

I agree.  

I probably won't have time to create the PR this week - if it is still open when I finish the first pass at the Java tools, I'll write something up.

**Comment by bact** [comment]
Agree with that and have a question on how to put this into a changelog?

Since this can be considered as a model change. 

Unless we declared that this is unintentional and it was supposed to be only one contentType (in Core), thus this is a "bug fix" and because of that there's no change in the model.

**Comment by bact** [comment]
I have open the PR #789 for this, based on @zvr detailed proposal.

Also add a CHANGELOG.md file in this repo to keep track things that specifically about the change in the model. If this is not a good idea to have it here, can remove/relocate.

**Comment by bact** [comment]
Note that `model/Software/Properties/contentType.md` has to be also removed from "nav:" section of [`mkdocs.yml`](https://github.com/spdx/spdx-spec/blob/development/v3.0.1/mkdocs.yml) in `spdx-spec` repo.
