### ISSUE TITLE
Punch List: Hash

### ISSUE THREAD

**Issue by iamwillbar** [spdx/spdx-3-model#8]
This is a punch list of open questions from the 2021-12-07 Tech Team meeting. Please comment on this issue with any discussion, proposed answers, or additional questions you have:

- [ ] Do we have all the hash algorithms we want?
- [x] Should hash value be string?  (should serializations supporting binary data be optimized?)
- [x] Do we want to include interpretations in the strings in the logical model?  
- [x] What are the serialization rules? (keeping it distinct from serialization - byte level)

**Comment by davaya** [comment]
Hash value is binary data.

Hash value can be serialized as a string (upper or lower case hex, with or without whitespace, base64, url-safe base64, etc.), all of which correspond to the same binary value.

This is equivalent to date/time being a single numeric value which can be serialized in many string formats, and IPv4 / IPv6 addresses which are 32 and 128-bit binary values that can be serialized in many text representations.

**Comment by seabass-labrax** [comment]
I agree with @davaya. Further to his comments, I would suggest that the individual serialisation specifications should mandate a certain representation for hashes, which would facilitate consistent round-tripping for ingestion and export of these formats. For instance:

> In JSON format, SHA256 hashes should be serialised as a string of 64 characters, containing a lower-case base 32 representation of the binary hash value.
> Example: `"hashValue": "499346e3caca25705e1a0e358bc89fe411c5b6345a644c308ef2cf2c0ee8c230",`

There's a potential discussion point as to whether this would be too constraining, but on balance I think the round-trip advantage would outweigh any stylistic concerns.

**Comment by davaya** [comment]
I agree.

The OpenC2 information model (https://docs.oasis-open.org/openc2/oc2ls/v1.0/cs02/oc2ls-v1.0-cs02.html#315-serialization) uses a "format" option to require a particular string representation.  By default binary values are required to be serialized as URL-safe base64, but using the "x" option (Binary /x) requires the string to be upper-case hex with no whitespace as specified in RFC 4648.  We're planning to update that so that upper-case /X requires RFC 4648 encoding and validation, while lower-case /x uses lower-case hex encoding and case-insensitive validation.

Any text-based serialization would use the same formats, and additional formats can be defined.  For example MAC address - Binary /eui - is required to be a 48 or 64 bit binary value represented as colon-separated hex bytes: 00:1B:44:11:3A:B7.  (This should also be relaxed - the IEEE spec allows no whitespace or hyphens between hex bytes.)

OpenC2 chose to use an integer number of milliseconds directly as a timestamp value rather than trying to require a particular text representation - there are so many of them that trying to parse them all for validation would be a major pain, and picking just one, like RFC 3339, is guaranteed to make someone mad :-).  But SPDX could choose to use an Integer or Number for logical timestamp values and a specific string format like RFC 3339 for text serialization.

**Comment by iamwillbar** [comment]
Decision in meeting 2022-01-04:
* Logical model uses byte array for hash values - intent: enable binary serialization formats
* Serialization model defines how to convert byte array to the serialization format
* Text-based formats should use a consistent serialization where possible
* Text-based serialization would use current text-based serialization (lowercase hex encoding without a prefix) - intent: compatibility with 2.2

**Comment by goneall** [comment]
Proposal we add the hash algorithms [supported by CycloneDX](https://cyclonedx.org/docs/1.4/json/#components_items_hashes_items_alg) to support higher fidelity interoperability.

**Comment by seabass-labrax** [comment]
@goneall, I'd be most supportive of that, especially as SPDX 3.0 will likely use the same text serialisation for hashes as CycloneDX (lower-case hex without a prefix).
