### ISSUE TITLE
Inconsistent use of camelCase in JSON Schema and JSON Context profile names

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#803]
In generating the prefixes for non core type names, the original camelCase naming is not preserved.

For example `simplelicensing_SimpleLicensingText` is used rather than `simpleLicensing_SimpleLicensingText`.

Was this intentional?

If so, it is OK, but we should document it since it is (at least to me) a bit unexpected and is creating a slight amount of work in my tooling efforts.

**Comment by goneall** [comment]
Ping @JPEWdev @zvr - let me know your thoughts on this one.

**Comment by goneall** [comment]
After thinking about this, keeping all lower case is actually easier - so I'm going to close this issue

**Comment by zvr** [comment]
It's definitely not done by accident, since the [code](https://github.com/spdx/spec-parser/blob/5bfa51a5c0e7b7fb978cb45607fc1c2d26915d08/spec_parser/rdf.py#L260) explicitly calls `lower()`.

I have no preference, either way.

I completely agree we have to document this -- as everything to do with the generated JSON-LD context. I've opened https://github.com/spdx/spdx-spec/issues/998 for this.
