### ISSUE TITLE
Change the name of Hash and hashAlgorithm back to Checksum and checksumAlgorithm

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#90]
From reviewing various articles on the differences between Hash and Checksum, it would appear that Checksum is intended for verification purposes and more appropriate to our usage here in SPDX.  For example, see the [Baeldung article on Hash vs. Checksum](https://www.baeldung.com/cs/hash-code-vs-checksum).

Not to mention, SPDX 1.0 and later versions use Checksum and checksumAlgorithm.  Changing to Hash and hashAlgorithm would introduce unnecessary migration efforts.

**Comment by seabass-labrax** [comment]
I believe that the Baeldung article is incorrect in its claim that checksums are "integrity-based hashing functions". There are plenty of integrity checking mechanisms that are not hash functions: Hamming codes, Cyclic Redundancy Checks, Reed-Solomon codes etc. None of these are in SPDX, where the 'checksum algorithm' choices are exclusively hash functions; in particular they are all cryptographic hash functions.

There are a number of SPDX stakeholders who wish to use SPDX for security purposes, ensuring that supply chain artefacts haven't been tampered with. Non-cryptographic checksums and hash functions can't detect malicious and deliberate modification, making them inadequate for this use-case.

All in all, I would say that calling these values in SPDX 3+ 'hashes' is more accurate, and in my opinion isn't going to introduce much in additional migration difficulty considering the structural changes.

**Comment by davaya** [comment]
I believe that the definition of a hash function is that it converts an arbitrary-length input to a fixed-length output, and that "cryptographic" is an adjective that distinguishes hashes useful against deliberate attack from those useful only against random modification.

[JanBask](https://www.janbasktraining.com/community/sql-server/explain-the-differences-as-well-as-the-similarities-between-checksum-vs-hash#:~:text=A%20checksum%20is%20intended%20to,against%20a%20very%20motivated%20attacker) takes the position that they are intrinsically different, and I think it is wrong.  It is definitely wrong in one respect: "A perfect hash function is injective, so there are no collisions."  That is nonsense because it is mathematically impossible to reduce an input to a smaller output without collisions.

"Cryptographic checksum" means exactly the same thing as "cryptographic hash" even though they have different connotations without the adjective.  And what do you call what was formerly thought to be a cryptographic hash that is now thoroughly broken against deliberate attack?  Is it still a "hash" or does it change from "hash" to "checksum"?

I prefer "checksum" because it implies purpose rather than mechanism, the way "integrity check value" separates purpose from algorithm (hash, authenticated hash (e.g. hmac), signature, etc.).  Also because it requires the reader to understand that there is not a black and white threshold above which the algorithm changes from "checksum" to "hash".

**Comment by goneall** [comment]
William and Gary will sync up on the topic

**Comment by goneall** [comment]
After sync'ing with William, I now agree with the name change based on a common understanding of the difference in purpose of a checksum and hash.

I updated the migration guide with a [justification for the change](https://docs.google.com/document/d/1-olHRnX1CssUS67Psv_sAq9Vd-pc81HF8MM0hA7M0hg/edit#heading=h.jt6wn5ruik8g).

If anyone feels like we should keep the checksum name, please open a new issue.
