### ISSUE TITLE
assessedElement to target SoftwareArtifact instead of Element

### ISSUE THREAD

**Issue by ilans** [spdx/spdx-3-model#911]
From /Security/assessedElement:
"Specifies subpackages, files or snippets ..."

If it's limited to only packages, files and snippets then why its target is Element and not SoftwareArtifact?

Package, File and Snippet are the only subclasses of SoftwareArtifact.

**Comment by zvr** [comment]
I think the target should be `/Core/Artifact`.

Since in the future we might have security info for other, non-software artifacts.

**Comment by kestewart** [comment]
Having it as Element is going to provide more flexibility for future profiles.   Ok to discuss further but at this point it's going to 4.0 related change.

**Comment by kestewart** [comment]
Removing the milestone until this is discussed.

**Comment by goneall** [comment]
Discussed on tech call 2024-12-03:

- We want to allow the future relationship to hardware - propose Artifact rather than SoftwareArtifact
- Going from more restrictive to less restrictive would not be a breaking change, so we could restrict to SoftwareArtifact today and add HardwareArtifact in 3.1 without it being a breaking change
- Requirement don't block the hardware profile
- Requirement that we don't block functional safety
- In general, don't block any other future profiles
- Propose: Go with more restrictive now, relax the restrictions with the new profiles - this won't be breaking changes, so we meet the requirements
- Specific change is to change range from "Element" to "SoftwareArtifact"
